# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043b78caa38f41ffbfda06dafd9620f2ab56886d59e259e6e110378ba49a93c24ed4f05abfa812919fb8bbb84186136fd78ac6c8f52d12ece6f0cf8cce986983

test:
  secret_key_base: 671a6fa8287a8109a609fdde725252042fc2370faf1f848df212b9a499934597c896626d3c29dc2234679fb5acac6c91664ecf52e100790170002611b13f2e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
